In [6]:
# making the necessary imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import os
import torch_geometric as tg
import torch_geometric.transforms as T
import networkx as nx

from data.Q2.CustomGraphDataset import CustomGraphDataset

In [8]:
import warnings
warnings.filterwarnings('ignore')

In [9]:
# loading the dataset from processed_data_old.pt
train_data = torch.load('data/Q2/train.pt')
val_data = torch.load('data/Q2/val.pt')
test_data = torch.load('data/Q2/test.pt')

In [11]:
print(train_data)
print(val_data)
print(test_data)

CustomGraphDataset(150)
CustomGraphDataset(19)
CustomGraphDataset(19)


tensor(23643)


In [24]:
print(f'{data_v1.edge_index[0][0:20]}\n{data_v1.edge_index[1][0:20]}')
middle = len(data_v1.edge_type)//2
print(f'{data_v1.edge_index[0][middle:middle+20]}\n{data_v1.edge_index[1][middle:middle+20]}')
last = len(data_v1.edge_type)
print(f'{data_v1.edge_index[0][last-20:last]}\n{data_v1.edge_index[1][last-20:last]}')

tensor([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5])
tensor([ 3733,  9748, 15066, 23086,   234, 10575, 15523, 21536, 17765, 22505,
          655,  5200,  9625, 21536, 10060, 10260, 12531, 21536,  6064,  9080])
tensor([12590, 12591, 12591, 12591, 12591, 12592, 12592, 12593, 12593, 12593,
        12593, 12594, 12594, 12594, 12594, 12595, 12595, 12595, 12595, 12595])
tensor([20164,  8561, 15880, 21536, 21700,  8827, 18396,  2847,  6936,  9288,
        21536,  3838, 13354, 20414, 21536,  1280,  4431,  8562, 15194, 18194])
tensor([23638, 23638, 23639, 23639, 23639, 23639, 23640, 23640, 23640, 23640,
        23641, 23641, 23641, 23641, 23642, 23642, 23643, 23643, 23643, 23643])
tensor([ 9459, 14588, 14303, 14424, 21536, 23120,  1703,  8774, 15055, 21536,
         5472,  7991, 16704, 21536,  9935, 11926,  5804, 16590, 17298, 23086])


In [6]:
print(data_v1.train_idx)

tensor([12971, 11751, 17534, 10835, 13373, 22544, 16421,  2063, 11373, 14379,
        19790, 11594,   612, 10364,  6632,  8654,  7264,   273,   480,  2774,
         3113, 13052,  8151, 17117, 16928,  8181, 21408, 22003, 13433, 15513,
        14481, 17849, 22012,  4230, 15343,  1206,  9594, 14798,  8774,  5274,
         9048,  7168, 12099,  7066,  3438,  9784,  7988,  9173, 15136, 11926,
         6321,  2999,  3794,  5635,  2596, 16201, 19861,  1064, 23389,  3309,
         6631,  5963, 18814, 15163,  8414, 15853,   353, 14990,  2719,  1529,
        20825, 17070, 10709, 13830,  9620, 20876,   458, 19894,  7779, 16674,
        17349, 13355,  8668,  4995,  7708,  4961,  3070,  1326, 14129,   434,
        16973, 16704,  2237, 20656,  9625,  1799,  4364, 18489, 10279, 10137,
        11238, 19075, 23093, 22545,  3736, 15726, 15187, 17249, 22597, 20121,
        22252,  1763, 19514, 14547, 10907, 18988,  8561,  2546,  6904,  8296,
        12194,  7721, 23287,  2238, 19554, 16895, 13519, 17211, 

In [8]:
print(data_v1.train_y)

tensor([1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
        1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
        0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
        1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0])


In [11]:
print(data_v1.val_idx)

tensor([12532,  6451,  6236, 10348, 13386, 22638, 18858, 18618,   402,   796,
        13669,   813, 17582, 18689,  3925,   801,  4339,   567, 14529, 18126,
        15478, 19325, 11207, 17007,  4215,   548, 16679, 18444, 14530, 13810,
        20489, 15681, 11436, 22147])


In [9]:
print(data_v1.val_y)

tensor([1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 1, 1, 0, 1, 0, 1, 1, 1, 1])


In [7]:
print(data_v2.y)

tensor([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1])


In [14]:
from torch_geometric.utils import to_networkx

In [27]:
G = to_networkx(data_v1, to_undirected=False)

In [28]:
print(G.number_of_edges())

146228


In [37]:
# make an undirected copy of the digraph
UG = G.to_undirected()

# extract subgraphs
sub_graphs = nx.connected_components(UG)
S = [UG.subgraph(c).copy() for c in sub_graphs]
print(len(S))

# for i, sg in enumerate(sub_graphs):
#     print("subgraph {} has {} nodes".format(i, sg.number_of_nodes()))
#     print("\tNodes:", sg.nodes(data=True))
#     print("\tEdges:", sg.edges())

2
